### ISSUE TITLE
Repeated spells and cantrips

### ISSUE THREAD

**Issue by Fontanapink** [safety-orange/Imports-for-MPMB-s-Character-Sheet#22] opened 2018-08-01 16:03 UTC
1st lvl druid spell:
Snare

Cantrips:
Infestation
Primal Savagery

**Comment by RobRoseKnows** [comment] 2018-08-01 18:45
Uh, can you elaborate?

**Comment by Fontanapink** [comment] 2018-08-01 18:49
Yeah! sorry about that.

When you are choosing cantrips and spells, some of them are repeated. I don't know if that's something specific from mpmb or here

**Comment by Shwaffle** [comment] 2018-08-01 19:01
This looks like a possible duplicate of the other open issue as well.

I believe this is specific to the sheet, and has been addressed in v13: https://www.reddit.com/r/mpmb/comments/81vqbp/three_subclasses_double_spells/

**Comment by Fontanapink** [comment] 2018-08-01 21:49
Cool! I'll just go ahead and close the issues.

BTW THANK YOU SO MUCH FOR YOUR WORK!!!! Everything is AMAZING

**Closed** 2018-08-01 21:51 UTC
